### ISSUE TITLE
Contact module

### ISSUE THREAD

**Issue by Stardog** [AppStateESS/phpwebsite#122]
Make a small module to contain contact information. Will be required on every uni site. Include phone link, address, map.

**Comment by Stardog** [comment]
This was silently added a while back. Closing. If you have feature requests or bugs, please post.

**Comment by trf000** [comment]
on a fresh install I'm getting an internal server error

Server Error

500 Internal Server Error

For URL /index.php method GET

Stack Depth	Line	File	Function	Class
0	61	/var/www/html/acweb/Global/PhpwebsiteController.php	__construct	Http\ErrorResponse
1	40	/var/www/html/acweb/index.php	execute	PhpwebsiteController
This error was originally caused by an uncaught exception "SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'" with code 23000 in file /var/www/html/acweb/Global/Database/Table.php on line 779.

Stack Depth	Line	File	Function	Class
0	779	/var/www/html/acweb/Global/Database/Table.php	execute	PDOStatement
1	234	/var/www/html/acweb/Global/Database/Engine/mysql/Table.php	insert	Database\Table
2	979	/var/www/html/acweb/Global/Database/DB.php	insert	Database\Engine\mysql\Table
3	68	/var/www/html/acweb/Global/Settings.php	insert	Database\DB
4	35	/var/www/html/acweb/Global/Settings.php	set	Settings
5	21	/var/www/html/acweb/Global/Settings.php	loadDefaultSettings	Settings
6	117	/var/www/html/acweb/mod/contact/class/Factory/ContactInfo.php	get	Settings
7	50	/var/www/html/acweb/mod/contact/Module.php	display	contact\Factory\ContactInfo
8	160	/var/www/html/acweb/Global/PhpwebsiteController.php	runTime	contact\Module
9	46	/var/www/html/acweb/Global/PhpwebsiteController.php	runTime	PhpwebsiteController
10	40	/var/www/html/acweb/index.php	execute	PhpwebsiteController
