### ISSUE TITLE
anchors being changed upon edit

### ISSUE THREAD

**Issue by trf000** [AppStateESS/phpwebsite#208]
Say I have a pagesmith page called faq. I have an anchor called Q1. My link to the anchor is faq#Q1. When i go back to edit the page, the link gets changed to 
"index.php?module=pagesmith&amp;aop=block_info&amp;pid=21&amp;bid=21&amp;section_id=document-text1#Q1"

It inserts correctly, but on edit, changes.

**Comment by Stardog** [comment]
I'll check it out.

**Comment by Stardog** [comment]
Here is the problem.
We use <base> with our url forwarding. Let's say you are at /blog/3 and you hover over a shortcut link for a page named "foobar" you get:
<code>http://yoursite.com/foobar</code>
This is perfect. The base tag translating "./foobar" into the above.
Now what happens if you do NOT have a base?
<code>http://yoursite.com/blog/3/foobar</code>
This is bad.
So we use base as a crutch. The problem is when you then use anchors.
<code><a href="#go-to-anchor">Go to anchor</a></code>
The Base tries to help by sending you to:
<code>http://yoursite.com/#go-to-anchor</code>
But we don't want to go there, we want to go to an anchor relative to where we are now.
So, PHPWS_Text has a setting in text_settings.php named FIX_ANCHORS. If true, it tries to help you by giving the anchor a full path. That is why you see that crazy path.
This message is mostly a brain dump to cross reference while I am looking at the code, but that is why you see that.

**Comment by trf000** [comment]
ok. i follow that.

seriously... i followed that.

On Mon, Feb 16, 2015 at 10:34 AM, Matthew McNaney <notifications@github.com>
wrote:

> Here is the problem.
> We use with our url forwarding. Let's say you are at /blog/3 and you hover
> over a shortcut link for a page named "foobar" you get:
> http://yoursite.com/foobar
> This is perfect. The base tag translating "./foobar" into the above.
> Now what happens if you do NOT have a base?
> http://yoursite.com/blog/3/foobar
> This is bad.
> So we use base as a crutch. The problem is when you then use anchors.
> Go to anchor <#14b933dd0e85fdaa_go-to-anchor>
> The Base tries to help by sending you to:
> http://yoursite.com/#go-to-anchor
> But we don't want to go there, we want to go to an anchor relative to
> where we are now.
> So, PHPWS_Text has a setting in text_settings.php named FIX_ANCHORS. If
> true, it tries to help you by giving the anchor a full path. That is why
> you see that crazy path.
> This message is mostly a brain dump to cross reference while I am looking
> at the code, but that is why you see that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppStateESS/phpwebsite/issues/208#issuecomment-74535612>
> .
>



-- 
Pretend inferiority and encourage his arrogance.
