### ISSUE TITLE
Cross-contamination question

### ISSUE THREAD

**Issue by Clintbaker** [AppStateESS/phpwebsite#254]
Hello,

I have inherited an old PHPWS installation that has been very customized.  I am grasping at straws and wondering if anyone who is well versed in it would be able to give me a suggestion as to where or what variables (SESSION, OBJ_LAYOUT, etc) to start.  

My problem is that when using the staffman module (realizing this may be a modification issue but hear me out) and managing more than one person in more than one tab, I can get cross-contamination across the tabs.  Let's say I have one tab on one user John Smith with ID=25.  In another tab I have another user Jane Doe with an ID=50.  It seems when I edit John Smith's and then save the data, it will overwrite with ID=50 erasing the Jane Doe identity.  It also seems to happen without tabs also and just picking up somehow an old recently viewed ID.  I can't determine when exactly it does it or exactly what the conditions are that cause it other than it seems to be not clearing out an old ID when I move to an new person's page where subsequent edits should be on the new person's ID.  Where would I look for this information or how would I do about forcing a reload thus clearing the old person's data in the variables?  Hopefully this at least makes some sense.

Many thanks for any help or pointers that anyone can provide.
Clint

**Comment by jlbooker** [comment]
Hi @Clintbaker,

What version of PHPWS are you running? It sounds like it's pretty old, in which case, the standard recommendation is to start by upgrading. You're likely running a very-outdated version of PHP (the language itself). Newer versions of PHPWS won't run on anything less than php 5.3.2. The older versions will certainly break at some point due to non-backwards compatible changes in the PHP language.

I can't recommend much running such an old version of PHP and PHPWS because of security and performance issues. You really _should_ update.

The staffman module is a third-party "community" module. They setup a project over on SourceForge to track its development. You might try opening an issue here instead: http://sourceforge.net/p/phpwebsite-comm/mod-staffman/   It doesn't seem to be updated frequently, but it might be worth a shot.

Unfortunately, I don't think I'll be able to help you because I don't have such an old version of PHPWS (nor PHP) setup where I could test and reproduce the issue.

**Comment by jlbooker** [comment]
I would suggest checking the `$_SESSION` variable though. In early versions of PHPWS, it was popular to use the session for lots of things (browers didn't have "tabs" back then). It sounds like the user id is being stored on the session, so interacting with one tab overwrites the user id on the session (and for any other tabs open).

**Comment by Clintbaker** [comment]
Thanks Jeremy!  Very very much appreciated!!!  I realize it is very old.  It’s been so customized that I don’t think it would survive an upgrade...

Clint

**Comment by trf000** [comment]
Staffman is pre 1.0. there is not 1.0 version of it. That's an old install.
like jurrasic old.

**Comment by Clintbaker** [comment]
Thanks. Yes it was from circa 2004. Then heavily modified.

Clint

**Comment by eberhardtm** [comment]
Clint,

I actually have a couple of these old installations running as well since the companies didn't want to upgrade.  They definitely do not play well with browser tabs.  Lots that depend on the use of sessions before tabbed browsing was a thing.

Just curious... Where did you inherit it from?

**Comment by Clintbaker** [comment]
Hey Ted. What did you mean?  We just took it as a code base to start our
own project. I'm just not really sure where to start to tackle the tabs
idea is all I suppose. If someone could point me to where and when this
started to change I can start a code behaviour comparison and try and nail
it down.

Clint
